---
title: 'why-test-my-code'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- Why test my code?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand how testing can help to ensure that code is working as expected

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction

Whether you are writing the occasional script or developing a large software, mistakes are inevitable. Sometimes you don't even know when a mistake creeps into the code, and it gets published. 

Consider the following function:

```python
def add(a, b):
    return a - b
```

This function is supposed to add two numbers. However when typing it out, I made a typo and I didn't notice it before adding this function to my project.

I could manually test this function by running it with different inputs and checking the output, but:

- This takes time
- I will forget to try every combination of inputs
- I will forget to test it again when I make changes to the code

Also, later on, when my code starts producing unexpected results, I will have to manually test every function to find the bug.

This is where automated testing comes in.

## Automated testing

Automated testing is where we write code, that tests our code. Every time we make a change, we can run our tests to make sure that our code still works as expected.

If we were writing a test from scratch for the `add` function, think for a moment on how we would do it.
We would need to write a function that runs the `add` function several times, checking each test case to ensure it does what we expect. We might write something like this:

```python
def test_add():
   if add(1, 2) != 3:
      print("Test failed!")
   if add(0, 0) != 0:
      print("Test failed!")
   if add(-1, -2) != -3:
      print("Test failed!")
```

Here we check that the function works for a set of test cases. This ensures that it works for positive numbers, negative numbers, and zero. We call this function a "test".

To make these kinds of functions simpler, there is a special statement in Python that makes this easier: the `assert` statement. This statement checks that an expression is true, and if it is not, it raises an error. We can use this to write our tests like this:

```python
def test_add():
   assert add(1, 2) == 3
   assert add(0, 0) == 0
   assert add(-1, -2) == -3
```

This test checks that the `add` function works as expected. If it doesn't, then the test will fail and we will know that we need to fix the function.

The `assert` statement just checks that the expression is true. If it is not, then the test fails. We will see more about this later.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

Inline instructor notes can help inform instructors of timing challenges
associated with the lessons. They appear in the "Instructor View"

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: challenge 

## Challenge 1: What might go wrong?

What is the output of this command?

(insert function that might fail here)

:::::::::::::::::::::::: solution 

## Output
 
(insert possible issues with the function here)

:::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: keypoints 

- Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::

